version: "2"
services:
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Prague
    volumes:
      - /ssd-data/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
  plex:
    container_name: plex
    image: plexinc/pms-docker 
    restart: unless-stopped
    environment:
      - TZ=Europe/Prague
      - PLEX_UID=1000
      - PLEX_GID=100
      # Home network, Docker bridge network
      - ALLOWED_NETWORKS=192.168.0.0/24,172.18.0.0/16
      - VERSION=docker
    network_mode: host
    volumes:
      - /ssd-data/plex:/config
      - /ssd-data/plex:/transcode
      - /Master/Media:/Media
  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Prague
    volumes:
      - /ssd-data/tautulli:/config
      - /ssd-data/plex/Library/Application Support/Plex Media Server/Logs:/logs
    restart: unless-stopped
    ports:
     - 8181:8181
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Prague
    volumes:
      - /ssd-data/bazarr:/config
      - /Master/Media/Movies:/movies
      - /Master/Media/Series:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Prague
    volumes:
      - /ssd-data/radarr/config:/config
      - /Master/Media/Movies:/movies
      - /ssd-data/radarr/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Prague
    volumes:
      - /ssd-data/sonarr/config:/config
      - /Master/Media/Series:/tv
      - /ssd-data/sonarr/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Prague
      - AUTO_UPDATE=true #optional
      #- RUN_OPTS=run options here #optional
    volumes:
      - /ssd-data/jackett/config:/config
      - /ssd-data/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Prague
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /ssd-data/deluge/config:/config
      - /ssd-data/deluge/downloads:/downloads
    restart: unless-stopped
